import "./globals.css";

import { ConvexClientProvider } from "./ConvexClientProvider";
import Footer from "./components/Footer";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
