import "./globals.css";

import CartModal from "./components/CartModal";
import { CartProvider } from "./context/CartContext";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Footer from "./components/Footer";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <CartProvider>
            <Navbar/>
            {children}
            <CartModal />
             <Toaster richColors position="top-right" />
            <Footer/>
          </CartProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
